export const algeriaStates = [
  { id: 1, name_ar: "أدرار", name_en: "Adrar" },
  { id: 2, name_ar: "الشلف", name_en: "Chlef" },
  { id: 3, name_ar: "الأغواط", name_en: "Laghouat" },
  { id: 4, name_ar: "أم البواقي", name_en: "Oum El Bouaghi" },
  { id: 5, name_ar: "باتنة", name_en: "Batna" },
  { id: 6, name_ar: "بجاية", name_en: "Béjaïa" },
  { id: 7, name_ar: "بسكرة", name_en: "Biskra" },
  { id: 8, name_ar: "بشار", name_en: "Béchar" },
  { id: 9, name_ar: "البليدة", name_en: "Blida" },
  { id: 10, name_ar: "البويرة", name_en: "Bouira" },
  { id: 11, name_ar: "تمنراست", name_en: "Tamanrasset" },
  { id: 12, name_ar: "تبسة", name_en: "Tébessa" },
  { id: 13, name_ar: "تلمسان", name_en: "Tlemcen" },
  { id: 14, name_ar: "تيارت", name_en: "Tiaret" },
  { id: 15, name_ar: "تيزي وزو", name_en: "Tizi Ouzou" },
  { id: 16, name_ar: "الجزائر", name_en: "Algiers" },
  { id: 17, name_ar: "الجلفة", name_en: "Djelfa" },
  { id: 18, name_ar: "جيجل", name_en: "Jijel" },
  { id: 19, name_ar: "سطيف", name_en: "Sétif" },
  { id: 20, name_ar: "سعيدة", name_en: "Saïda" },
  { id: 21, name_ar: "سكيكدة", name_en: "Skikda" },
  { id: 22, name_ar: "سيدي بلعباس", name_en: "Sidi Bel Abbès" },
  { id: 23, name_ar: "عنابة", name_en: "Annaba" },
  { id: 24, name_ar: "قالمة", name_en: "Guelma" },
  { id: 25, name_ar: "قسنطينة", name_en: "Constantine" },
  { id: 26, name_ar: "المدية", name_en: "Médéa" },
  { id: 27, name_ar: "مستغانم", name_en: "Mostaganem" },
  { id: 28, name_ar: "المسيلة", name_en: "M'Sila" },
  { id: 29, name_ar: "معسكر", name_en: "Mascara" },
  { id: 30, name_ar: "ورقلة", name_en: "Ouargla" },
  { id: 31, name_ar: "وهران", name_en: "Oran" },
  { id: 32, name_ar: "البيض", name_en: "El Bayadh" },
  { id: 33, name_ar: "إليزي", name_en: "Illizi" },
  { id: 34, name_ar: "برج بوعريريج", name_en: "Bordj Bou Arréridj" },
  { id: 35, name_ar: "بومرداس", name_en: "Boumerdès" },
  { id: 36, name_ar: "الطارف", name_en: "El Tarf" },
  { id: 37, name_ar: "تندوف", name_en: "Tindouf" },
  { id: 38, name_ar: "تيسمسيلت", name_en: "Tissemsilt" },
  { id: 39, name_ar: "الوادي", name_en: "El Oued" },
  { id: 40, name_ar: "خنشلة", name_en: "Khenchela" },
  { id: 41, name_ar: "سوق أهراس", name_en: "Souk Ahras" },
  { id: 42, name_ar: "تيبازة", name_en: "Tipaza" },
  { id: 43, name_ar: "ميلة", name_en: "Mila" },
  { id: 44, name_ar: "عين الدفلى", name_en: "Aïn Defla" },
  { id: 45, name_ar: "النعامة", name_en: "Naâma" },
  { id: 46, name_ar: "عين تموشنت", name_en: "Aïn Témouchent" },
  { id: 47, name_ar: "غرداية", name_en: "Ghardaïa" },
  { id: 48, name_ar: "غليزان", name_en: "Relizane" },
  { id: 49, name_ar: "تيميمون", name_en: "Timimoun" },
  { id: 50, name_ar: "برج باجي مختار", name_en: "Bordj Badji Mokhtar" },
  { id: 51, name_ar: "أولاد جلال", name_en: "Ouled Djellal" },
  { id: 52, name_ar: "بني عباس", name_en: "Béni Abbès" },
  { id: 53, name_ar: "عين صالح", name_en: "In Salah" },
  { id: 54, name_ar: "عين قزام", name_en: "In Guezzam" },
  { id: 55, name_ar: "تقرت", name_en: "Touggourt" },
  { id: 56, name_ar: "جانت", name_en: "Djanet" },
  { id: 57, name_ar: "المغير", name_en: "El M'Ghair" },
  { id: 58, name_ar: "المنيعة", name_en: "El Meniaa" },
]
